version: '3.8'

services:
  app:
    build: .
    command: >
      sh -c "
      python3 avanzatech_blog/manage.py makemigrations &&
      python3 avanzatech_blog/manage.py migrate &&
      python3 avanzatech_blog/manage.py shell < setup.py && 
      python3 avanzatech_blog/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/avanzatech_blog
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  pgdata:
