# Generated by Django 5.0.1 on 2024-03-05 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
        ('post', '0006_postcategorypermission'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='postcategorypermission',
            unique_together={('post', 'category')},
        ),
    ]
