# Generated by Django 5.0.1 on 2024-03-11 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0005_alter_comment_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
    ]
