# Generated by Django 5.0.1 on 2024-01-23 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_post_read_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_permission',
            field=models.CharField(choices=[('public', 'anyone can access the post'), ('authenticated', 'any authenticated user can access the post'), ('team', 'Any user on the same team as the post author can access the post'), ('author', 'Only the author can access the post')], default='anyone can access the post', max_length=20),
        ),
    ]
