# Generated by Django 5.0.1 on 2024-01-23 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_alter_post_read_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='modified_date',
            new_name='modified_at',
        ),
    ]
