# Generated by Django 5.0.1 on 2024-01-23 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_rename_created_date_post_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='modified_at',
            new_name='last_modified',
        ),
    ]
