# Generated by Django 5.0.1 on 2024-01-28 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0004_remove_like_status_like_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='like',
            options={'ordering': ['-created_at']},
        ),
    ]
