# Generated by Django 5.0.1 on 2024-01-28 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('like', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='status',
        ),
        migrations.AddField(
            model_name='like',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
