# Generated by Django 5.0.1 on 2024-01-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='status',
            field=models.CharField(choices=[('active', 'resource is active'), ('inactive', 'resource is not active')], default='active', max_length=10),
        ),
    ]
